document.writeln("<footer>");
document.writeln("			<div class=\'container\'>");
document.writeln("				<div class=\'row\'>");
document.writeln("					<div class=\'col-sm-6\'>");
document.writeln("						<div class=\'footer-body  ak-news-footer\'>");
document.writeln("							<h3 class=\'margin-bottom-20\'>");
document.writeln("								<img src=\'../upload/201706/1497260553.png\' class=\'img-responsive\'/>");
document.writeln("							</h3>");
document.writeln("							<p class=\'footer-service-code\'>更多详情请关注官方服务号</p>");
document.writeln("							<h3 class=\'margin-bottom-20\'>");
document.writeln("								<img src=\'../upload/img/weixin.jpg\' class=\'img-service\' style=\'max-height: 100px;\'>");
document.writeln("							</h3>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'visible-xs-block height-20\'></div>");
document.writeln("					<div class=\'col-sm-6 contact\'>");
document.writeln("						<div class=\'footer-body\'>");
document.writeln("							<h3 class=\'title\' style=\'font-size: 16px;font-weight: 600;\'>CONTACT</h3>");
document.writeln("							<p>");
document.writeln("								<i class=\'icon pe-map-marker\' aria-hidden=\'true\'></i> 上海市徐汇区田林东路75号汇阳广场518室");
document.writeln("							</p>");
document.writeln("							<p>");
document.writeln("								<i class=\'icon pe-call\' aria-hidden=\'true\'></i> 4006-817-813");
document.writeln("							</p>");
document.writeln("							<p>");
document.writeln("								<i class=\'icon pe-mail\' aria-hidden=\'true\'></i>");
document.writeln("								<a href=\'mailto:info@amazontx.com\' rel=\'nofollow\'>beiku@amazontx.com</a>");
document.writeln("							</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</footer>");